name: advanced_flutter_template
description: A new Flutter project with advanced setup.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flex_color_scheme: ^6.1.2
  font_awesome_flutter: ^10.3.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  provider: ^6.0.5
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16

flutter:
  assets:
    - assets/
  generate: true
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#000000"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000"
  image: assets/icon.png
