name: Run tests

on:
  push:

jobs:
  build_android:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: '3.32.8'
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: flutter test
